HomeWork2
AlexisKozlov/tms pull request #1
Opened 2022-02-18 13:25 UTC by AlexisKozlov

1. Task
2. 
![image](https://user-images.githubusercontent.com/71926607/154690830-80bc1512-362e-4d62-b05a-39c7c65c0b8d.png)
 
P.s. Не вышло сделать по позиционированию, пока не знаю как.

2022-02-18 18:16 UTC, shuliakleonid requested changes

2022-02-18 18:16 UTC, shuliakleonid commented on style.css
> +}
comments in your code is bad practice

2022-02-18 18:16 UTC, shuliakleonid commented on style.css
> +} */
if you need comments that's all right

2022-02-18 18:16 UTC, shuliakleonid commented
## Good work!

2022-02-18 19:00 UTC, AlexisKozlov commented on style.css
> +}
> FIxed

2022-02-19 09:48 UTC, shuliakleonid approved these changes

2022-02-20 09:41 UTC, egkirpichev approved these changes

2022-02-21 09:16 UTC, KseniaKotova approved these changes
Good going!

2022-02-22 16:02 UTC, merged